# structure of the table for the final catalgoue
import numpy as np
from astropy.table import Table, Column

# build the table structure
columns = [
    Column(name="SOURCE_NAME", data=None, dtype="str", unit=""),
    Column(name="RA", data=None, dtype="float64", unit="deg"),
    Column(name="DEC", data=None, dtype="float64", unit="deg"),
    Column(name="SOURCE_TYPE", data=None, dtype="str", unit=""),
    Column(name="LoTSS-MORX-ID", data=None, dtype="str", unit=""),
    Column(name="VLASS-MORX-ID", data=None, dtype="str", unit=""),
    Column(name="NVSS-ID", data=None, dtype="str", unit="", description="from SIMBAD"),
    Column(name="FIRST-ID", data=None, dtype="str", unit="", description="from SIMBAD"),
    Column(name="SDSS-ID", data=None, dtype="str", unit="", description="from SIMBAD"),
    Column(name="MORX-XMM-ID", data=None, dtype="str", unit=""),
    Column(name="4XMM-DR14-ID", data=None, dtype="str", unit="", description="updating info in MORX"),
    Column(name="MORX-CXO-ID", data=None, dtype="str", unit=""),
    Column(name="CSC2.1-ID", data=None, dtype="str", unit="", description="updating info in MORX"),
    Column(name="MORX-SWIFT-ID", data=None, dtype="str", unit=""),
    Column(name="2SXPS-ID", data=None, dtype="str", unit="", description="updating info in MORX"),
    Column(name="BAT-157-Month-ID", data=None, dtype="str", unit=""),
    Column(name="Simbad-FERMI-ID", data=None, dtype="str", unit="",description="from Simbad"),
    Column(name="1FLT-ID", data=None, dtype="str", unit=""),
    Column(name="TORESSI DETECTION", data=None, dtype="bool", unit=""),
    Column(name="4XMM Variability Flag", data=None, dtype="str", unit=""),
    Column(name="Chandra Variability", data=None, dtype="str", unit=""),
    Column(name="LOBE EXTENSION", data=None, dtype="float64", unit="mas",description="Sky extent of longer lobe in milliarcseconds"),
    Column(name="DISTANCE", data=None, dtype="float64", unit="Mpc"),
    Column(name="Log10(L_OIII)", data=None, dtype="float64", unit="erg s-1"),
    Column(name="NVSS-FLUX-XMATCH", data=None, dtype="float64", unit="erg s-1"),
    Column(name="NVSS-FLUX-ERROR-XMATCH", data=None, dtype="float64", unit="erg s-1"),
    Column(name="FIRST-FLUX-XMATCH", data=None, dtype="float64", unit="erg s-1"),
    Column(name="FIRST-FLUX-ERROR-XMATCH", data=None, dtype="float64", unit="erg s-1"),
    Column(name="4XMM Flux (2-4.5 keV)", data=None, dtype="float64", unit="erg s-1",description="mean flux (2.0 - 4.5 keV) of all the detections of the source SRCID"),
    Column(name="4XMM Flux (2-4.5 keV) Error", data=None, dtype="float64", unit="erg s-1"),
    Column(name="4XMM Flux (4.5-12 keV)", data=None, dtype="float64", unit="erg s-1",description="mean flux (4.5 - 12.0 keV) of all the detections of the source SRCID"),
    Column(name="4XMM Flux (4.5-12 keV) Error", data=None, dtype="float64", unit="erg s-1"),
    Column(name="4XMM HR_3", data=None, dtype="float64", unit="",description="1-2 keV and 2-4.5 keV energy band hardness ratio"),
    Column(name="4XMM HR_3e", data=None, dtype="float64", unit="",description="1-2 keV and 2-4.5 keV energy band hardness ratio"),
    Column(name="4XMM HR_4", data=None, dtype="float64", unit="",description="2-4.5 keV and 4.5-12 keV energy band hardness ratio"),
    Column(name="4XMM HR_4e", data=None, dtype="float64", unit="",description="2-4.5 keV and 4.5-12 keV energy band hardness ratio"),
    Column(name="CSC2.1 Flux (0.5-7 keV)", data=None, dtype="float64", unit="erg s-1",description="Fitted Absorbed PL Flux"),
    Column(name="CSC2.1 Flux LowErr", data=None, dtype="float64", unit="erg s-1",description="68 lower confidence limit"),
    Column(name="CSC2.1 Flux UppErr", data=None, dtype="float64", unit="erg s-1",description="68 upper confidence limit"),
    Column(name="CSC2.1 PhoIndex", data=None, dtype="float64", unit="",description="Fitted Absorbed PL Photon Index"),
    Column(name="CSC2.1 PhoIndex L_err", data=None, dtype="float64", unit="",description="68 lower confidence limit"),
    Column(name="CSC2.1 PhoIndex U_err", data=None, dtype="float64", unit="",description="68 upper confidence limit"),
    Column(name="CSC2.1 HR (HM)", data=None, dtype="float64", unit="",description="hard (2-7 keV) and medium (1.2-2.0 keV) energy band hardness ratio."),
    Column(name="CSC2.1 HR (HM) L_err", data=None, dtype="float64", unit=""),
    Column(name="CSC2.1 HR (HM) U_err", data=None, dtype="float64", unit=""),
    Column(name="SWIFT Flux (0.3-10 keV)", data=None, dtype="float64", unit="erg s-1",description="mean 0.3-10keV observed flux assuming the power-law spectral model fitted to a custom-built spectrum"),
    Column(name="SWIFT Flux (0.3-10 keV) LowErr", data=None, dtype="float64", unit="erg s-1"),
    Column(name="SWIFT Flux (0.3-10 keV) UppErr", data=None, dtype="float64", unit="erg s-1"),
    Column(name="SWIFT Photon Index", data=None, dtype="float64", unit="",description='The spectral photon index inferred assuming the power-law spectral model fitted to a custom-built spectrum'),
    Column(name="SWIFT Photon Index LowErr", data=None, dtype="float64", unit=""),
    Column(name="SWIFT Photon Index UppErr", data=None, dtype="float64", unit=""),
    Column(name="SWIFT HR2", data=None, dtype="float64", unit="",description="hard (2-10 keV) and medium (1-2 keV) band count rates hardness ratio"),
    Column(name="SWIFT HR2 L_err", data=None, dtype="float64", unit=""),
    Column(name="SWIFT HR2 U_err", data=None, dtype="float64", unit=""),
]
coreG_catalogue = Table(columns)
fr0_catalogue = Table(columns)
