# structure of the table for the final catalgoue
import numpy as np
from astropy.table import Table, Column

class CatalogBuilder():

    def __init__(self, table):
        self.table = table

    def add_source(self, source_name, luminosity):
        self.table.add_row((source_name, luminosity))

# build the table structure
table = [
    Column(name="SOURCE_NAME", data=None, dtype="str", unit=""),
    Column(name="SOURCE_TYPE", data=None, dtype="str", unit=""),
    Column(name="NVSS-ID", data=None, dtype="str", unit="", description="from SIMBAD"),
    Column(name="FIRST-ID", data=None, dtype="str", unit="", description="from SIMBAD"),
    Column(name="SDSS-ID", data=None, dtype="str", unit="", description="from SIMBAD"),
    Column(name="MORX-XMM-ID", data=None, dtype="str", unit=""),
    Column(name="4XMM-DR14-ID", data=None, dtype="str", unit="", description="updating info in MORX"),
    Column(name="MORX-CXO-ID", data=None, dtype="str", unit=""),
    Column(name="CSC2.1-ID", data=None, dtype="str", unit="", description="updating info in MORX"),
    Column(name="MORX-SWIFT-ID", data=None, dtype="str", unit="")
    Column(name="2SXPS-ID", data=None, dtype="str", unit="", description="updating info in MORX"),
    Column(name="LoTSS-MORX-ID",
    Column(name="VLASS-MORX",
    Column(name="TORESSI DETECTION",
    Column(name="4XMM Variability Flag",
    Column(name="Chandra Variability",
    Column(name="LOBE EXTENSION",
    Column(name="DISTANCE",
    Column(name="FERMI-ID", data=None, dtype="str", unit=""),
    Column(name="1FLT-ID", data=None, dtype="str", unit=""),
    Column(name="Log10(L_OIII)",
    Column(name="NVSS-FLUX-XMATCH",
    Column(name="NVSS-FLUX-ERROR-XMATCH",
    Column(name="FIRST-FLUX-XMATCH",
    Column(name="FIRST-FLUX-ERROR-XMATCH",
    Column(name="4XMM-DR14 L_1",
    Column(name="4XMM-DR14 L_1e",
    Column(name="4XMM-DR14 L_2",
    Column(name="4XMM-DR14 L_2e",
    Column(name="4XMM-DR14 L_3",
    Column(name="4XMM-DR14 L_3e",
    Column(name="4XMM-DR14 L_4",
    Column(name="4XMM-DR14 L_4e",
    Column(name="4XMM-DR14 L_5",
    Column(name="4XMM-DR14 L_5e",
    Column(name="4XMM-DR14 L_8",
    Column(name="4XMM-DR14 L_8e",
    Column(name="4XMM-DR14 L_9",
    Column(name="4XMM-DR14 L_9e",
    Column(name="4XMM-DR14 HR_1",
    Column(name="4XMM-DR14 HR_2",
    Column(name="4XMM-DR14 HR_3",
    Column(name="4XMM-DR14 HR_4",
    Column(name="4XMM-DR14 Number of Detections",
    Column(name="CSC2.1 Fitted Absorbed PL Flux",
    Column(name="CSC2.1 Fitted Absorbed PL Flux L_err",
    Column(name="CSC2.1 Fitted Absorbed PL Flux U_err",
    Column(name="CSC2.1 Fitted Absorbed PL PhoIndex",
    Column(name="CSC2.1 Fitted Absorbed PL PhoIndex L_err",
    Column(name="CSC2.1 Fitted Absorbed PL PhoIndex U_err",
    Column(name="CSC2.1 Flux Broad",
    Column(name="CSC2.1 Flux Broad L_err",
    Column(name="CSC2.1 Flux Broad U_err",
    Column(name="CSC2.1 Flux Hard",
    Column(name="CSC2.1 Flux Hard L_err",
    Column(name="CSC2.1 Flux Hard U_err",
    Column(name="CSC2.1 Flux Medium",
    Column(name="CSC2.1 Flux Medium L_err",
    Column(name="CSC2.1 Flux Medium U_err",
    Column(name="CSC2.1 Flux Soft",
    Column(name="CSC2.1 Flux Soft L_err",
    Column(name="CSC2.1 Flux Soft U_err",
    Column(name="CSC2.1 Flux Ultrasoft",
    Column(name="CSC2.1 Flux Ultrasoft L_err",
    Column(name="CSC2.1 Flux Ultrasoft U_err",
    Column(name="CSC2.1 Hardness Ratio HM",
    Column(name="CSC2.1 HR HM L_err",
    Column(name="CSC2.1 HR HM U_err",
    Column(name="CSC2.1 Hardness Ratio HS",
    Column(name="CSC2.1 HR HS L_err",
    Column(name="CSC2.1 HR HS U_err",
    Column(name="CSC2.1 Hardness Ratio MS",
    Column(name="CSC2.1 HR MS L_err",
    Column(name="CSC2.1 HR MS U_err",
    Column(name="SWIFT Mean Broad Flux Fitted PL",
    Column(name="SWIFT Mean Broad Flux Fitted PL L_err",
    Column(name="SWIFT Mean Broad Flux Fitted PL U_err",
    Column(name="SWIFT Mean Broad Flux PL",
    Column(name="SWIFT Mean Broad Flux PL L_err",
    Column(name="SWIFT Mean Broad Flux PL U_err",
    Column(name="SWIFT HR1',
    Column(name="SWIFT HR1 L_err',
    Column(name="SWIFT HR1 U_err',
    Column(name="SWIFT HR2',
    Column(name="SWIFT HR2 L_err',
    Column(name="SWIFT HR2 U_err',
    Column(name="SOURCE_NAME", data=None, dtype="str", unit="")
    Column(name="LUMINOSITY", data=None, dtype=np.float64, unit="erg s-1")


catalog_builder = CatalogBuilder(table)
catalog_builder.add_source("Source_A", 1e42)
catalog_builder.add_source("Source_B", 1e43)

import IPython; IPython.embed()

"""
catalogue = Table(
    names=(
        "SOURCE_NAME",
        "SOURCE_TYPE",
        "SIMBAD SDSS-ID",
        "SIMBAD FERMI-ID",
        "Fermi Transient 1FLT",
        "SIMBAD NVSS-ID",
        "NVSS-XMATCH-ID",
        "NVSS-MORX-ID",
        "SIMBAD FIRST-ID",
        "FIRST-XMATCH-ID",
        "FIRST-MORX-ID",
        "XMM-MORX-ID",
        "4XMM-DR14-ID",
        "CXO-MORX-ID",
        "Chandra 1.1",
        "CSC 2.1 ID",
        "SWIFT-MORX-ID",
        "2SXPS Swift ID",
        "LoTSS-MORX-ID",
        "VLASS-MORX",
        "TORESSI DETECTION",
        "4XMM Variability Flag",
        "Chandra Variability",
        "LOBE EXTENSION",
        "DISTANCE",
        "Log10(L_OIII)",
        "NVSS-FLUX-XMATCH",
        "NVSS-FLUX-ERROR-XMATCH",
        "FIRST-FLUX-XMATCH",
        "FIRST-FLUX-ERROR-XMATCH",
        "4XMM-DR14 L_1",
        "4XMM-DR14 L_1e",
        "4XMM-DR14 L_2",
        "4XMM-DR14 L_2e",
        "4XMM-DR14 L_3",
        "4XMM-DR14 L_3e",
        "4XMM-DR14 L_4",
        "4XMM-DR14 L_4e",
        "4XMM-DR14 L_5",
        "4XMM-DR14 L_5e",
        "4XMM-DR14 L_8",
        "4XMM-DR14 L_8e",
        "4XMM-DR14 L_9",
        "4XMM-DR14 L_9e",
        "4XMM-DR14 HR_1",
        "4XMM-DR14 HR_2",
        "4XMM-DR14 HR_3",
        "4XMM-DR14 HR_4",
        "4XMM-DR14 Number of Detections",
        "CSC2.1 Fitted Absorbed PL Flux",
        "CSC2.1 Fitted Absorbed PL Flux L_err",
        "CSC2.1 Fitted Absorbed PL Flux U_err",
        "CSC2.1 Fitted Absorbed PL PhoIndex",
        "CSC2.1 Fitted Absorbed PL PhoIndex L_err",
        "CSC2.1 Fitted Absorbed PL PhoIndex U_err",
        "CSC2.1 Flux Broad",
        "CSC2.1 Flux Broad L_err",
        "CSC2.1 Flux Broad U_err",
        "CSC2.1 Flux Hard",
        "CSC2.1 Flux Hard L_err",
        "CSC2.1 Flux Hard U_err",
        "CSC2.1 Flux Medium",
        "CSC2.1 Flux Medium L_err",
        "CSC2.1 Flux Medium U_err",
        "CSC2.1 Flux Soft",
        "CSC2.1 Flux Soft L_err",
        "CSC2.1 Flux Soft U_err",
        "CSC2.1 Flux Ultrasoft",
        "CSC2.1 Flux Ultrasoft L_err",
        "CSC2.1 Flux Ultrasoft U_err",
        "CSC2.1 Hardness Ratio HM",
        "CSC2.1 HR HM L_err",
        "CSC2.1 HR HM U_err",
        "CSC2.1 Hardness Ratio HS",
        "CSC2.1 HR HS L_err",
        "CSC2.1 HR HS U_err",
        "CSC2.1 Hardness Ratio MS",
        "CSC2.1 HR MS L_err",
        "CSC2.1 HR MS U_err",
        "SWIFT Mean Broad Flux Fitted PL",
        "SWIFT Mean Broad Flux Fitted PL L_err",
        "SWIFT Mean Broad Flux Fitted PL U_err",
        "SWIFT Mean Broad Flux PL",
        "SWIFT Mean Broad Flux PL L_err",
        "SWIFT Mean Broad Flux PL U_err",
        'SWIFT HR1',
        'SWIFT HR1 L_err',
        'SWIFT HR1 U_err',
        'SWIFT HR2',
        'SWIFT HR2 L_err',
        'SWIFT HR2 U_err',
    ),

       
    dtype=[
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        str,
        bool,
        str,
        str,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
        np.float64,
    ],
    
    units=[
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "mas",
        "Mpc",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "",
        "",
        "",
        "",
        "",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "",
        "",
        "",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "erg s-1",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
)
"""